### PR TITLE
Allow creating a SecAccessControl with a protection

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by kornelski** [comment]
Could it use a more specific type than CFTypeRef?

**Comment by alex** [comment]
I'm not sure :-) `CFTypeRef` is what the underlying C API uses. Do you have a thought as to how we might model it differently here?

**Comment by kornelski** [comment]
I'm not familiar with that API. In general in the higher level wrapper I'd prefer to hide ObjC-isms and have type safety where possible.

What kind of objects are you passing there? Where do you get them from?

**Comment by alex** [comment]
For my use case, I'm passing a `CFString`: `kSecAttrAccessibleWhenUnlockedThisDeviceOnly`

**Comment by kornelski** [comment]
So that's an enum:

https://developer.apple.com/documentation/security/keychain_services/keychain_items/item_attribute_keys_and_values#1679100

**Comment by alex** [comment]
Ok, now uses an enum.

**Comment by kornelski** [comment]
Thanks

**Comment by alex** [comment]
Thank you!

**Pull request merged**
