### PR TITLE
SMJobBless

### PR DESCRIPTION
**Pull request by hankbao**
Since we cannot do `as_concrete_TypeRef()` on `Authorization`, I guess implementing `SMJobBless` directly within it would be okay.

### CODE REVIEW

**Comment by kornelski** [comment]
Thanks for the PR. 


Why the string type changes? Taking both str and CStringRef is odd.

**Comment by kornelski** [comment]
Also it'd be nice to return the boolean from smjobbbless.

**Comment by hankbao** [comment]
> Why the string type changes? Taking both str and CStringRef is odd.

That's because `domain` could only be `kSMDomainSystemLaunchd`, a `CFStringRef` exported by service-management-sys (from ServiceManagement.framework). So taking `domain` as a `CStringRef` would be more straightforward here.

> Also it'd be nice to return the boolean from smjobbbless.

If `SMJobBless` fail, an error from `CFError` will be returned. Same behavior as the `SecTransformSetAttribute` call in `SecTransform:: set_attribute`.

**Comment by kornelski** [comment]
Is `kSMDomainSystemLaunchd` literally the only useful value, or is `kSMDomainUserLaunchd` usable too? If only one, then you could just hardcode it inside the function. If both, you could make a Rust enum for them. It would be nice not to use ObjC types in a higher-level Rust API, especially that it's not just any string, but a specific key, so it should offer more type-safety than ObjC does.

As for returning a bool, I mean returning `Result<bool, …>`

**Comment by kornelski** [comment]
Oh, I see. I've misinterpreted the docs and thought the `true` worked like `hashmap.insert` result.

**Comment by kornelski** [comment]
service-management-sys doesn't compile on iOS

**Comment by kornelski** [comment]
Right. Fixed 438db710bcadff9327bad2b3aa3ba68d427b2d0d

**Pull request merged**
