### PR TITLE
Upgrade to bitflags 2

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by kornelski** [comment]
This may not be fully semver-compatible, and I'd rather not make major release for such detail.

**Comment by alex** [comment]
I believe with the added derives, it should be compatible. Not sure how to prove that though

**Comment by alex** [comment]
As a note, I believe this fixes a clippy warning. When it gets merged, I'll do a follow up to get clippy and teh rest of CI green.

**Comment by TxMat** [comment]
Also fixes a cargo deny warning

image

**Comment by TxMat** [comment]
Thanks !

**Pull request merged**
